### ISSUE TITLE
Support for CH340G Serial-to-USB Chips

### ISSUE THREAD

**Issue by DRSDavidSoft** [ksksue/PhysicaloidLibrary#30]
Some Arduino Clones use CH340G Serial to USB Chips, with DTR pin also connected.

Could you take a look at the following drivers and add it to Physicaloid? That way we can upload HEX files using both CP chips and CH34x chips.

[/usbserial/driver/Ch34xSerialDriver.java](https://github.com/mik3y/usb-serial-for-android/blob/master/usbSerialForAndroid/src/main/java/com/hoho/android/usbserial/driver/Ch34xSerialDriver.java)

[/usbserial/CH34xSerialDevice.java](https://github.com/felHR85/UsbSerial/blob/master/usbserial/src/main/java/com/felhr/usbserial/CH34xSerialDevice.java)

<hr>

**Update:** This issue already has a solution here: https://github.com/xxxajk/PhysicaloidLibrary/issues/2

**Comment by DRSDavidSoft** [comment]
Upon further inspection this fork seems to support CH340G:
https://github.com/ideniden/PhysicaloidLibrary

* People googling, you can use that.
* @ksksue, please merge that fork into the main branch for future uses.

**Comment by shabadsobti** [comment]
I was not able to get it to work. Any cues?

**Comment by DRSDavidSoft** [comment]
@shabad – https://github.com/xxxajk/PhysicaloidLibrary/pull/1#issuecomment-363651988

**Comment by xxxajk** [comment]
I'm quite busy at the moment working on some UHS30 code, some of which has been on hold for 1 year or more. Soon as I get a few things out of the way, I do plan on doing a push to the repo that includes some extras, such as serial over wifi/ethernet, and a serial on bluetooth skeleton.
WinChip Head support is next on my list today.

**Comment by xxxajk** [comment]
Please carry on discussion [here](url), as I am pretty sure that this account has been forgotten, and since I have been making more progress than anyone else with this library.
Thanks!

**Comment by DRSDavidSoft** [comment]
⚠ **PLEASE NOTE**
##### →  This issue is now CLOSED here. ←
- _Since both @ksksue and @ideniden seem to have gotten out of radar,
all discussions have been moved here: https://github.com/xxxajk/PhysicaloidLibrary/issues/2._
- For more follow-ups, read the wonderful work by @xxxajk.

<hr>

✅  _If the original author decides to come back from the dead at any moment, we'd like to encourage merging back the more active forks into the main branch._

Fore more information, click here: https://github.com/xxxajk/PhysicaloidLibrary/issues/2
