### ISSUE TITLE
doesn't always connect to the arduino

### ISSUE THREAD

**Issue by xseignard** [ksksue/PhysicaloidLibrary#6]
Hello,
I'm trying to use your lib in a phonegap/cordova plugin. So far the plumbing seems ok since I see the execution of my plugin, but I can connect to the serial port only a few times. I don't get what I'm doing wrong.

Here is the source: https://github.com/xseignard/cordovaSerial/blob/master/src/fr/drangies/cordova/serial/Serialoid.java

Any idea?

Regards

**Comment by xxxajk** [comment]
Which library exactly? I have many :-)

On Thu, Nov 21, 2013 at 9:46 PM, Xavier Seignard
notifications@github.comwrote:

> Hello,
> I'm trying to use your lib in a phonegap/cordova plugin. So far the
> plumbing seems ok since I see the execution of my plugin, but I can connect
> to the serial port only a few times. I don't get what I'm doing wrong.
> 
> Here is the source:
> https://github.com/xseignard/cordovaSerial/blob/master/src/fr/drangies/cordova/serial/Serialoid.java
> 
> Any idea?
> 
> Regards
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ksksue/PhysicaloidLibrary/issues/6
> .

## 

Visit my github for awesome Arduino code @ https://github.com/xxxajk

**Comment by xseignard** [comment]
the PhysicaloidLibrary, the one related with these issues. I don't get your question?!

**Comment by xxxajk** [comment]
Ahh, okay, so then this isn't about me, but ksksue, sorry, I got confused.

On Thu, Nov 21, 2013 at 9:59 PM, Xavier Seignard
notifications@github.comwrote:

> the PhysicaloidLibrary, the one related with these issues. I don't get
> your question?!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ksksue/PhysicaloidLibrary/issues/6#issuecomment-29045559
> .

## 

Visit my github for awesome Arduino code @ https://github.com/xxxajk

**Comment by ksksue** [comment]
Hi xseignard
You might want to do physicaloid.open() only when physicaloid.isOpened() == false.
