### ISSUE TITLE
Cannot Open

### ISSUE THREAD

**Issue by siljack** [ksksue/PhysicaloidLibrary#9]
Dear admin:
Sorry to bother i am a newbie here. Currently trying to send my data from Arduino Mega to Andriod Samsung S2 via USB. 

Does anyone face any problem while using Physicaloid library where the  device is set not to open at all time? 
Why i keep receiving the "Cannot Open" message even when i didnt even change anything in the code. 
I am even try all the tutorial example in this library but all also give the same message "Cannot Open". Is there anything that need to be aware when importing the library?

Any Advice is welcome...

**Comment by paczek137** [comment]
Try to use older version of the library.

**Comment by josejuansanchez** [comment]
Hello,

I have the same issue. I have tried to execute the PhysicaloidTest on a Nexus 7 connected to an Arduino Uno but without success. Always, I get the "Cannot open device" message error.

@paczek137 What version of the library I should use? Where can I find it?

Thanks in advance!

**Comment by siljack** [comment]
@paczek137 : Do you have the copy of the old library? Cause i cant find it anywhere around.
@josejuansanchez : Yeah i also don't understand whats going on. Hoping to have some clarification from the admin also.

**Comment by josejuansanchez** [comment]
@siljack A few days ago, @kwaka1208 posted an url where you can download an older version of the library: 

https://drive.google.com/file/d/0B92YYJtXXd45OU1hakxOSkVhWDg/edit?usp=sharing

I have tried it and it works fine.

**Comment by kasbah** [comment]
I had the same issue on an Asus Memo HD7 and linking against the .jar from google-drive is what worked.  @kwaka1208 do you know what version that is so we can fix this regression?

**Comment by paczek137** [comment]
Tab "commits" - there's a list of all PhysicaloidLibrary versions .
In each version you have access to browse code and download the full library.

**Comment by moheshmohan** [comment]
yep i had the same issue. just grab the version committed on Nov 22, 2013 and it will work

**Comment by siljack** [comment]
@moheshmohan Yeah thanks for the advice, it works now. But i still hope the admin can change back the updated one to a general usable version.
